# This is a one-off workflow to destroy everything in AWS with CDK.
# This is so that we don't incur unnecessary costs
name: 99 - Manually destroy AWS Stacks

on:
  workflow_dispatch

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Bootstrap CDK
    if: github.ref == 'refs/heads/main'
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'

      - name: NPM install
        working-directory: cdk
        run: npm install

      - name: Destroy Service
        working-directory: cdk
        run: npm run service:deploy

      - name: Destroy Dynamo
        working-directory: cdk
        run: npm run dynamo:destroy

      - name: Destroy Canary
        working-directory: cdk
        run: npm run canary:deploy

      - name: Destroy Monitoring
        working-directory: cdk
        run: npm run monitoring:deploy

      - name: Destroy Deployment Sequencer
        working-directory: cdk
        run: npm run deployment-sequencer:deploy

      - name: Destroy Domain
        working-directory: cdk
        run: npm run domain:deploy

      - name: Destroy ActiveMQ
        working-directory: cdk
        run: npm run activeMq:deploy

      - name: Destroy messaging
        working-directory: cdk
        run: npm run messaging:deploy

      - name: Destroy Database
        working-directory: cdk
        run: npm run database:deploy

      - name: Destroy Cognito
        working-directory: cdk
        run: npm run cognito:deploy

      - name: Destroy Certificate
        working-directory: cdk
        run: npm run certificate:deploy

      - name: Destroy Network
        working-directory: cdk
        run: npm run network:deploy

      - name: Destroy repository
        working-directory: cdk
        run: npm run repository:deploy
